// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdpdMv6kqKKalmyIuqq_gHFVPinFVKzHQ',
    appId: '1:591444926690:android:4b316e6ad8907904e7febb',
    messagingSenderId: '591444926690',
    projectId: 'agriclinichub',
    storageBucket: 'agriclinichub.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1hnZ9FtHZCgWRy7QRj7jH5NJP5NK3-u8',
    appId: '1:591444926690:ios:97ba11329bc84895e7febb',
    messagingSenderId: '591444926690',
    projectId: 'agriclinichub',
    storageBucket: 'agriclinichub.firebasestorage.app',
    iosBundleId: 'com.example.agriclinichubNew',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALu4-McRdODuq9Kx2L-1L8gCQ103zpRQI',
    appId: '1:591444926690:web:762feab32d194333e7febb',
    messagingSenderId: '591444926690',
    projectId: 'agriclinichub',
    authDomain: 'agriclinichub.firebaseapp.com',
    storageBucket: 'agriclinichub.firebasestorage.app',
    measurementId: 'G-GPLDLDM68B',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC1hnZ9FtHZCgWRy7QRj7jH5NJP5NK3-u8',
    appId: '1:591444926690:ios:97ba11329bc84895e7febb',
    messagingSenderId: '591444926690',
    projectId: 'agriclinichub',
    storageBucket: 'agriclinichub.firebasestorage.app',
    iosBundleId: 'com.example.agriclinichubNew',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyALu4-McRdODuq9Kx2L-1L8gCQ103zpRQI',
    appId: '1:591444926690:web:7cfd5d2c04d08e1be7febb',
    messagingSenderId: '591444926690',
    projectId: 'agriclinichub',
    authDomain: 'agriclinichub.firebaseapp.com',
    storageBucket: 'agriclinichub.firebasestorage.app',
    measurementId: 'G-S1K5X0FQWT',
  );

}